version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2/
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-central
      - plugin-portal
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
